name = "chefnam-email-worker"
main = "src/index.js"
compatibility_date = "2024-05-15"
account_id = "090ff2bbc69fa3773a65881f1decb269"

[env.production.vars]
ALLOWED_ORIGINS = "https://chefnamcatering.com,https://www.chefnamcatering.com"